apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app
  labels:
    app: argocd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-app
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
     nodeSelector:
       role: worker
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: argocd-app
        image: stoyanovsavvy/savvytribe:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-app-svc
spec:
  type: NodePort
  selector:
    app: gradle-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
